### ISSUE TITLE
Add Selector Object

### ISSUE THREAD

**Issue by watilde** [watilde/jsss-compiler#8]
I'd like to add `Selector Object` can specify any selectors.

e.g)

``` js
selectors['input button.prime:hover'].color ='red';
```

to

``` css
input button.prime:hover {
  color: red;
}
```
